"""Add game_user Association Table

Revision ID: 8662a49ea148
Revises: f55c82a6c53b
Create Date: 2023-12-07 14:04:31.805615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8662a49ea148'
down_revision = 'f55c82a6c53b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
