"""Add game_user Association Table

Revision ID: f55c82a6c53b
Revises: 6a01f0e1399f
Create Date: 2023-12-07 13:43:14.127383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55c82a6c53b'
down_revision = '6a01f0e1399f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
